### ISSUE TITLE
Question about rand_btwn_int()

### ISSUE THREAD

**Issue by bangerth** [dklong-csu/mepbm#19]
You currently have this:
```
// A function given two real numbers returns a random number
// between those numbers based on a uniform distribution
int rand_btwn_int (const double small_num, const double big_num)
{
  static std::mt19937 gen;
  std::uniform_int_distribution<> unif(small_num,big_num);

  return unif(gen);
}
```
Did you mean the function arguments to be `int` types? I suspect so, and the constructor arguments to `unif` are also `int`s, so whatever you pass as `double` values here will get converted to integers ayway.

**Comment by dklong-csu** [comment]
Yes, you're correct about my intention. I wrote the `double` version first and copy-pasted to make the `int` version. I must have been tired and missed some of the changes I needed to make.

**Comment by bangerth** [comment]
Put it on your list of things to fix!
